var utsGanjil20 = [ 
    {
        title: 'Aljabar Linear',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1Yz6PW79474MKTbaahW0TBkDVB2bfHY4D/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Analisis Vektor dan Bilangan Kompleks',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/19TzclpVrjyS5c0Ob5odk3L3G8w8B1cuE/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Analisis Vektor dan Bilangan Kompleks (Tekkom)',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1YUi7LwrIUARkZb_3YQ0xWPxS6OGF-nCi/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Dasar Sistem Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1GvN-oih0ixyBiWqODa779cgLXT8NUNgP/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1iO7mks78gmYYn0jWF186nRl3cauO5Fl4/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Kalkulus',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1obCpAJut-0v0j6Mcrz4dMyB6dKUCAoPQ/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Matematika Teknik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1pPchRiKXuUHHV4k4Tto7Askeve1LoGPV/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Probabilitas dan Proses Stokastik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1BJd8s5CJyWmolcwIHacITp778VYtYUKe/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik (Tekkom)',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1ToBgKubZBUbCouN7O217hRDbILXUWG4U/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Kimia Dasar',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1nRPN434MgWQ4ThAPzoA698Heoo7VdZtO/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_11.jpg',
        link: 'https://drive.google.com/file/d/1LdZcZcgQ4FcfEp0-jmTTnUoo5oq8U2CM/view?usp=sharing',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]

var uasGanjil20 = [
    {
        title: 'Analisis Vektor dan Peubah Kompleks Elektro',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1Yz6PW79474MKTbaahW0TBkDVB2bfHY4D/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Analisis Vektor dan Peubah Kompleks Tekkom',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/19TzclpVrjyS5c0Ob5odk3L3G8w8B1cuE/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Aljabar Linear',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1KJhqhwESDtE4MHbnyOTo2SOK2-XKBa_A/view',
        display: 'block',
    },
    {
        title: 'Kalkulus',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1GvN-oih0ixyBiWqODa779cgLXT8NUNgP/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Dasar Sistem Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1o_hgdAsEfoheUEFWV2eSgBIlQ1FLTYiB/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1YezF4oAIE52dD_bPBEE0YNMs8Dhgkn7L/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Probabilitas dan Proses Stokastik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1-E-70nU0HUBFe4H7DNeA_mH9IXyJS4Ts/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Matematika Teknik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1dJ3fzImzAXUnKIOD_buwizU_nOBFD7Dv/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Kimia Dasar',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1Urpi04nnLokoHb_RkUY3IN2p3XGd1jc_/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1t9dySjexfJKM2bOzsf9G0XyMUd2WpM2e/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik Tekkom',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1kxH28i5nTwDJ-AvoNCDe3k19uRRSxb86/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_4.jpg',
        link: 'https://drive.google.com/file/d/1F6WG5OnitvPrMRJpfn3_lqk5O2KlSBFN/view?usp=sharing',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]

var utsGenap20 = [ 
    {
        title: 'Aljabar Linear',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1WiFP8XP3mtoIRIMdwGzkBaQPrlRZMl0c',
        display: 'block',
    },
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1rFANnSmS6vcFRw9PvKPzmom8BMtkUjhG',
        display: 'block',
    },
    {
        title: 'MPKT-A (Ringkasan)',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1DnMbrbzxVQr9LZz9RXyiPas1hX0QhITn',
        display: 'block',
    },
    {
        title: 'Pengantar Teknik komputer',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1O0E_k2c4Hg_M_B8k7P2i6nAMp6Yr2JL_',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1weQMbdZUyS0dfawAuqWFZp_2JvFB2L6Q',
        display: 'block',
    },
    {
        title: 'Sistem Berbasis Komputer',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1tWe8gIY4HCes6wvSGjZe4BE_chgb7jjr',
        display: 'block',
    },
    {
        title: 'Agama Islam (Ringkasan)',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1LQ6gaqOzPBqni_FT_mjPC0rIYJN19OXM',
        display: 'block',
    },
    {
        title: 'Elektromagnetika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1ozq7_sV3rB-XD_wlLrmkE09TjzL_b0mO',
        display: 'block',
    },
    {
        title: 'Kimia Dasar',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1cleGbzpBHfAMtejBncjp4fL84FZ3rwF0',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 1',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1SYUkfN2tkqe7Q1ZkN8ZDkevCfQqI-PJi',
        display: 'block',
    },
    {
        title: 'Sinyal dan Sistem',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_9.jpg',
        link: 'https://drive.google.com/open?id=1wi_lVpIShzMXM-uyOEku3cUCO8259gYr',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]
var uasGenap20 = [ 
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/1fCugCZPaeY_d7P0nEYdyma9wYvWCKulI/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Kimia Dasar',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/1oEJ1iLNJ6zNcHuAeAg-iKtkxaZb7IVR0/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'MPKT-A',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/1eoQMLjk02IrnvpqLo6CzUf1D1SxOiNL4/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Aljabar Linear',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/1WVB7Ckh_oF_BqipDzy7PiPPsf9zLea5I/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Elektromagnetika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/1PTFsro5iuq5fZFR35-xyh5Aj5hV1cmAS/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Pengantar Teknik Komputer',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/11HtBjzSIvlh37niCV_gaCYfjE6uym3l8/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Dasar Sistem Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/1KZ4ksQvrgD1yM4GhYrk04rI4NBbpAjP0/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 1',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/1gCEkErKSSykmnMDuwes-v3Wgk-9QNTUA/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/1Bpue961Up6bp-MCBqPjbBXjYemz8_yXG/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Sinyal dan Sistem',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_3.jpg',
        link: 'https://drive.google.com/file/d/1q0iuFIc8fJToQbkCiR7a0U-1rKQHbYIM/view?usp=sharing',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]
//----------------------------------------------------------------------------------------------------------2019-------------------------------------------------------------------//
var utsGanjil19 = [ 
    {
        title: 'Analisis Vektor dan Bilangan Kompleks',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=1eiA9i0Q1YQknb9de_DQNtyEIWUNW0Knh',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=1QFugJX_A4iAwy2EVAP4nfb2exzONcQNl',
        display: 'block',
    },
    {
        title: 'Dasar Sistem Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=1w2-XL-v3IvuluMiqRfAxGE63WWYkc3ry',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=1pLA7GBiBgX90cvfC6OW4si5M3vDvkceb',
        display: 'block',
    },
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=1MvH8xK9Z7gX1f_HOTKuHPndjEGlAyn7u',
        display: 'block',
    },
    {
        title: 'Kalkulus',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=1sSZlDhgLh0eyki0zomYVYwUfEJpYr8od',
        display: 'block',
    },
    {
        title: 'Matematika Teknik ',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=18QOihFW4bYPddkb70SLJBUiNQMky71DZ',
        display: 'block',
    },
    {
        title: 'Probabilitas dan Proses Stokastik ',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=1wXCHSomlIreV7MBlSrK4-PCEVRSKQVUD',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik (Tekkom)',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=18bSZjh2txEM7dbmXat3uci5Gfy71L-XJ',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=1XD0DLAd8KF79ndai5VPHFntzyEZbQdAD',
        display: 'block',
    },
    {
        title: 'Statistik dan Probabilistik ',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_0.jpg',
        link: 'https://drive.google.com/open?id=13ivJX3VNm0CCAcfOeQtMxla-q17w9Gmb',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]
var uasGanjil19 = [ 
    {
        title: 'Analisis Vektor dan Peubah Kompleks',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_7.jpg',
        link: 'https://drive.google.com/open?id=1MdYWfsYz3JQsGyQH1BiHECKrJLiTXdmJ',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_7.jpg',
        link: 'https://drive.google.com/open?id=1JYUxQZDW2mNgrfWAqMuOB5-IDDjGScdx',
        display: 'block',
    },
    {
        title: 'Dasar Sistem Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_7.jpg',
        link: 'https://drive.google.com/open?id=1VZd-rIrrgcYYJVrR9lUDj12uWfvJ0o6Q',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_7.jpg',
        link: 'https://drive.google.com/open?id=1Ppqwu7uKtAQr1m8EQHx0Ljo8foa2rZVW',
        display: 'block',
    },
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_7.jpg',
        link: 'https://drive.google.com/open?id=1sIx8ooAhc9dRDaPZgy3CCdKcbJhZbd1T',
        display: 'block',
    },
    {
        title: 'Matematika Teknik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_7.jpg',
        link: 'https://drive.google.com/open?id=1anz9LCnPwOPsIbayaU4gnnnOveEjg73w',
        display: 'block',
    },
    {
        title: 'Probabilitas dan Proses Stokastik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_7.jpg',
        link: 'https://drive.google.com/open?id=1xl63LoWDzT0ShQZieTYjbcmik74Epv_Q',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_7.jpg',
        link: 'https://drive.google.com/open?id=1mslPqFCH8PzYVGu3BzrGFQRu9XJKwUFG',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]
var utsGenap19 = [ 
    {
        title: 'Aljabar Linear',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=1Mk_uFECVlzp2QFDVsDpVWdAyFwGH7p9p',
        display: 'block',
    },
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=1EwBycuMnInAl1c36NsHIRxFgwmmK47KI',
        display: 'block',
    },
    {
        title: 'MPKT-A',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=1dm8ul2kU0JoFoCMhMRYJAKIR3cGzxp77',
        display: 'block',
    },
    {
        title: 'Pengantar Teknik Komputer',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=1NhROhcPIU1Iq01l8EYsdePHPXqij6aCv',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=1QCLJfjamGajrhRE7bSE1pKN-Cqup4on9',
        display: 'block',
    },
    {
        title: 'Sistem Berbasis Komputer',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=1Cexlu8HhYdgibgCRifPOXjOjQYcxligc',
        display: 'block',
    },
    {
        title: 'Agama Islam',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=18QOihFW4bYPddkb70SLJBUiNQMky71DZ',
        display: 'block',
    },
    {
        title: 'Elektromagnetika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=1gBSRyddc7AWY_HnVn79XhK2bm12zRtOr',
        display: 'block',
    },
    {
        title: 'Kimia Dasar',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=18RCtfbVIQW3qZXzdH3uFmT-ZOrw3RxRD',
        display: 'block',
    },
    {
        title: 'Material Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=1ILBAC3tBhoPOfjVQc7zmO6FxG0gS3S_j',
        display: 'block',
    },
    {
        title: 'Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=12z5GIpf6AydPksKJ32-tthfhH37z7i9U',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 1',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=1rOi7zQXznpJfcBtPSvhqJGevatBYCt2M',
        display: 'block',
    },
    {
        title: 'Sinyal dan Sistem',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_10.jpg',
        link: 'https://drive.google.com/open?id=134_DIAKMwF24ZIXa_UVFdT0kSe-iKQS3',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]
var uasGenap19 = [ 
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1zGVqtQdwGpZy4FiGMOB9viWkkXPMzko2',
        display: 'block',
    },
    {
        title: 'Kimia Dasar',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=12SaY7SRUUkBSGDKx3TSKKsz041Bm0wx8',
        display: 'block',
    },
    {
        title: 'Material Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1Brdo6Az_Ja9aUcXCD3fnxGlWzyEKBHO5',
        display: 'block',
    },
    {
        title: 'MPKT-A',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1bNCPOq3JIes_ZRcxdvOYhrb-UtC18Ycq',
        display: 'block',
    },
    {
        title: 'Agama Islam',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1oWlboVNrpZfj_0gfVWI8jTwg02elZHnL',
        display: 'block',
    },
    {
        title: 'Aljabar Linear',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1vPo2SDmI1BPb2fehm_Ehl-wrq4Wi9SY-',
        display: 'block',
    },
    {
        title: 'Elektromagnetika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1AYSg5kXO7CKSN4aa8g9Rw156QuHJObwJ',
        display: 'block',
    },
    {
        title: 'Pengantar Teknik Komputer',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1P4Qy5XFWnWb3177vCn46ZYKKWQCCNYGJ',
        display: 'block',
    },
    {
        title: 'Rangkaian Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1g5ZHqujAx_mgwsQ6llhq10n79b4SVf0X',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 1',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1xCILjZupsDyIQOHXxZ8-5N6nnCYSAEbH',
        display: 'block',
    },
    {
        title: 'Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1bSF-MA7gUK1pHo01NrIvbi90UeOWMvAN',
        display: 'block',
    },
    {
        title: 'Sinyal dan Sistem',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1HyVT1Qqodxi5YFasYEMyMzC9DdKaTKtx',
        display: 'block',
    },
    {
        title: 'Solusi Lengkap Diktat PTkom',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_2.jpg',
        link: 'https://drive.google.com/open?id=1hm4-Lcg4TYHQnMtT7i_r4WlGk7aH23eh',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]

//----------------------------------------------------------------------------------------------------------2018-------------------------------------------------------------------//
var utsGanjil18 = [ 
    {
        title: 'Analisis Vektor dan Bilangan Kompleks',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/file/d/1W64iejF7fNIE_Onz_Xmg6eNkg5PICYxJ/view',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1iQjqTfRSdK51UWcrDEwAXZzKTwkRVdo7',
        display: 'block',
    },
    {
        title: 'Dasar Sistem Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1-imoseZIFG73bZJSR1BATT6sMMpBfPUw',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1q4yuy5SnMX-AkbV3N7HmEoWeHFMLD6pw',
        display: 'block',
    },
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1MvH8xK9Z7gX1f_HOTKuHPndjEGlAyn7u',
        display: 'block',
    },
    {
        title: 'Kalkulus',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1KvfCZjjv13BIPz6-BtQpB79VQKPqRhtA',
        display: 'block',
    },
    {
        title: 'Matematika Teknik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1-ZEAK8Kr_JR8XNaqPe-H2k2r8J_sTucj',
        display: 'block',
    },
    {
        title: 'Probabilitas dan Proses Stokastik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1G0e9Gq7HkK8qumGjK05Id3Cmwjf3C61U',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik (Tekkom)',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1eS9l5-ebVDvM-DZvsoVjqS4pklmUwKa-',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1jA6wK4h2kcuBxPhqSPgnHowjN6DfXDrZ',
        display: 'block',
    },
    {
        title: 'MPKT-B',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_13.jpg',
        link: 'https://drive.google.com/open?id=1JjFsxWCI6AQXkKoGPZHuyBss1DzYEanB',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]
var uasGanjil18 = [ 
    {
        title: 'Analisis Vektor dan Peubah Kompleks',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_6.jpg',
        link: 'https://drive.google.com/open?id=1hPgyIC7w5fA0duYVa51odAaUp9xZ_XRN',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_6.jpg',
        link: 'https://drive.google.com/open?id=1hXM5RQA6EuOZ6B1RN8Z40GhWIsQJcAQm',
        display: 'block',
    },
    {
        title: 'Dasar Sistem Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_6.jpg',
        link: 'https://drive.google.com/open?id=1QXaXjQC_G1619dcHkCyHmkGXZuk4Cutu',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_6.jpg',
        link: 'https://drive.google.com/open?id=1qgkZ44AZ1rM-bzrB1UC3Kalp8p5ErWLN',
        display: 'block',
    },
    {
        title: 'Kalkulus',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_6.jpg',
        link: 'https://drive.google.com/open?id=199hixPnF4kShe-NHdx1RRFNrKXupztbo',
        display: 'block',
    },
    {
        title: 'Matematika Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_6.jpg',
        link: 'https://drive.google.com/open?id=1hgzY7P9tmnA2pRrIsiKnNXfHVixJ38YR',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_6.jpg',
        link: 'https://drive.google.com/open?id=13Cwg9pcC0cEOsEgsRUzVdtbkOOnL_taF',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]
var utsGenap18 = [ 
    {
        title: 'Aljabar Linear',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=1IFR6ZNYr37m4ZQAWl1Z626-vVmMxsZTt',
        display: 'block',
    },
    {
        title: 'Catatan Aljabar Linear',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=13ZZukBeG9BgRRMvDMiF1ofPWuT_uLKI4',
        display: 'block',
    },
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=1VXPzY6_JZKOaGTXF4zau8Qt_Z1RA-gg6',
        display: 'block',
    },
    {
        title: 'Agama',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=1u_LksiW9_hPifcjfFK1zAFsVVuHwDEpm',
        display: 'block',
    },
    {
        title: 'Dasar Komputer',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=1D3qdaQUppycNDQr4O7CCi5xymzpqg5lJ',
        display: 'block',
    },
    {
        title: 'Elektromagnetika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=1IOWpvkXdmatpSi1HtU1im2QjaxY7ukpW',
        display: 'block',
    },
    {
        title: 'Material Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=1jrUKmSdUpeCxw018pLvMhXGRc72CWUx6',
        display: 'block',
    },
    {
        title: 'Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=1HmBIbbn1U0u5r33IaADzaCW7BTpcFn7j',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 1',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=1WfSlNGV9Z9GrAdQpWORasAJY3X78pUT2',
        display: 'block',
    },
    {
        title: 'Sinyal dan Sistem',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_12.jpg',
        link: 'https://drive.google.com/open?id=14w8u_ZZ9Om-JJTxzk6DgjpQU3Mt5dFIA',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]
var uasGenap18 = [ 
    {
        title: 'Aljabar Linear',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1sKgIqD4zTpUYcmRJioTmjI3HV8YkwrkL/view',
        display: 'block',
    },
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1ShFZZKYIbGqzGz5js_Kxz2bdwYAos6mm/view',
        display: 'block',
    },
    {
        title: 'Agama Islam',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1CbqwK8uIQDg3IuiJNvXHJ-KCW_4mPL1B/view',
        display: 'block',
    },
    {
        title: 'Rangkuman MPK Agama Islam',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1NvFjNjBzPrmJJaVbAkFzCLcA-X7zUc_W/view',
        display: 'block',
    },
    {
        title: 'Dasar Komputer',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1z73Kz7EI48P5vdBhNjdpxrOvh2rlldfn/view',
        display: 'block',
    },
    {
        title: 'Elektromagnetika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1qgo6nWuVZkd7wEU7Bdxh6ZZaJqzZB67f/view',
        display: 'block',
    },
    {
        title: 'Material Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1o0jL6woNG2tbPUxIotC-DWUzvOuvZa6B/view',
        display: 'block',
    },
    {
        title: 'Rangkaian Elektronika',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1Wh2la9n26mzfjb5toT20lzFDxrvnu9wE/view',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 1',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1G5NVLXk7mfDzx5BmBghPsIX3LLX0ob2b/view',
        display: 'block',
    },
    {
        title: 'Sinyal dan Sistem',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_5.jpg',
        link: 'https://drive.google.com/file/d/1BA0HvT8yCcdQiCu_ZbpEOeglUwwo7M5w/view',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]

//----------------------------------------------------------------------------------------------------------2017-------------------------------------------------------------------//
var utsGanjil17 = [ 
    {
        title: 'Dasar Sistem Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_1.jpg',
        link: 'https://drive.google.com/file/d/1hhw8hBBAia-5jAvzu2ANq2OHKN2qxcML/view',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_1.jpg',
        link: 'https://drive.google.com/file/d/1Bs0i91BvjXVAaZ2yDOa_cut0QoTrs9xX/view',
        display: 'block',
    },
    {
        title: 'Fisika Mekanika dan Panas',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_1.jpg',
        link: 'https://drive.google.com/file/d/1MvH8xK9Z7gX1f_HOTKuHPndjEGlAyn7u/view',
        display: 'block',
    },
    {
        title: 'Kalkulus',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_1.jpg',
        link: 'https://drive.google.com/file/d/1JqXIu2Eyu9NYOSH_CwbpX2vvGeB-GZWK/view',
        display: 'block',
    },
    {
        title: 'Matematika Teknik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_1.jpg',
        link: 'https://drive.google.com/file/d/1rCFP-j2_OU3ZQ3AsfpV_VJufegh0eYYZ/view',
        display: 'block',
    },
    {
        title: 'Probabilitas dan Proses Stokastik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_1.jpg',
        link: 'https://drive.google.com/file/d/1rbEY3sNieUwoel-GdevguCSZWP53Jo3H/view',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 1',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_1.jpg',
        link: 'https://drive.google.com/file/d/11AoWWWxj5VXThz_RB0qcaqEYOiYYt75F/view',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_1.jpg',
        link: 'https://drive.google.com/file/d/1LkeEM2DhIiriy5fN_Ig19Qn-sc06DMAG/view',
        display: 'block',
    },
    {
        title: 'Teknik Kendali',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_1.jpg',
        link: 'https://drive.google.com/file/d/1qj-wz9s6YxJBI9CAtvNWNFybmC8dGRdK/view',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]
var uasGanjil17 = [ 
    {
        title: 'Dasar Sistem Digital',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/1rcbCYdnL2csD2dwgUn7LQFhzGFsdl7u-/view',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/1LTGoMW8Zp-VdzU3Pq4JZLzXllnqiKTBl/view',
        display: 'block',
    },
    {
        title: 'Analisis Vektor',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/1_qyaPObvKZ_4Qv2AKfKKwYMCbZs5A6J8/view',
        display: 'block',
    },
    {
        title: 'Kalkulus',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/1LpzOoajNO3Sm2lp4nYQjcK1QDRCvWSA-/view',
        display: 'block',
    },
    {
        title: 'Matematika Teknik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/1KrIkZxm4KrnqB0Gf_pkXBqJKg26bcv6_/view',
        display: 'block',
    },
    {
        title: 'Probabilitas dan Proses Stokastik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/10UYblRBN5PCWKDSOqxKKCmPZzbQJrz9N/view',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 1',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/1taso8iOk8Co4gPB9fuiXY8lC12f50Mvr/view',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/18Z89ZXAJpWrCFmC_2SVGdhOz0in2zXW0/view',
        display: 'block',
    },
    {
        title: 'Teknik Kendali',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/1ea0oc5fTOtV_exn6RZtFFLkuina7PYko/view?usp=drive_open',
        display: 'block',
    },
    {
        title: 'Teknik Telekomunikasi',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/1FFxkjRS5VK067UjZ7qFvFpTHH-SpSOM2/view',
        display: 'block',
    },
    {
        title: 'Teknik Tenaga Listrik',
        img: 'https://ime.eng.ui.ac.id/wp-content/uploads/84/2021/02/cover-diktattt_210220_8.jpg',
        link: 'https://drive.google.com/file/d/1pE3PZ6HJCthu6-rynoflaHrQ302ndtiQ/view',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]